<a href="https://colab.research.google.com/github/Woos-star/git_practice/blob/master/heatmap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import numpy as np
import pandas as pd
import locale

import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

# csvファイルを読み込んでdfへ入れる(DataFrameオブジェクト)
df = pd.read_csv('No_10_D1_E.csv', encoding="utf_8",header = 0)
#usecols=[2,3,4,5,6,7,8]
# df.Tで行と列を入れ替える
#print(df.T)

df1 = pd.read_csv('No_10_D1_E.csv', encoding="utf_8",header = 0 ,usecols=[2,3,6,7])
print(df1.T)
#usecols=[2,3,5,6,7,8]
#要素がgroupが1, 1,2,3,4,5 -> n
# col 2,3,2,3
#全体刺激回数分布図
sumMap = np.zeros((3,15))
#振動回数分布図
vibeMap = np.zeros((3,15))
otherTacMap = np.zeros((3,15))
painMap=np.zeros((3,15))
nonfeelingMap = np.zeros((3,15))
for col in df1.values:
    #group is 1
    if col[0] == 1:
      #  print(col)
        #nに刺激点指定
        n = col[1]
        #n-1をして式を簡単に
        mod = (n-1)%3
        share = (n-1)//3
        sumMap[(3-1)-(mod),(5-1)-share] = sumMap[(3-1)-(mod),(5-1)-share] +1
        if col[2] == 2 and col[3] == 1:
            vibeMap[(3-1)-(mod),(5-1)-share] = vibeMap[(3-1)-(mod),(5-1)-share] +1
        elif col[2] == 1:
            painMap[(3-1)-(mod),(5-1)-share] = painMap[(3-1)-(mod),(5-1)-share] +1
        elif col[2] == 3:
            nonfeelingMap[(3-1)-(mod),(5-1)-share] = nonfeelingMap[(3-1)-(mod),(5-1)-share] +1
        elif col[2] == 2 and col[3] == 2:
            otherTacMap[(3-1)-(mod),(5-1)-share] =otherTacMap[(3-1)-(mod),(5-1)-share] +1
    elif col[0] == 2:
        n = col[1]
        mod = (n-1)%3
        share = (n-1)//3
        sumMap[(3-1)-(mod),(5-1)-share+2] = sumMap[(3-1)-(mod),(5-1)-share+2] +1
        if col[2] == 2 and col[3] == 1:
            vibeMap[(3-1)-(mod),(5-1)-share+2] = vibeMap[(3-1)-(mod),(5-1)-share+2] +1
        elif col[2] == 1:
            painMap[(3-1)-(mod),(5-1)-share+2] = painMap[(3-1)-(mod),(5-1)-share+2] +1
        elif col[2] == 3:
            nonfeelingMap[(3-1)-(mod),(5-1)-share+2] = nonfeelingMap[(3-1)-(mod),(5-1)-share+2] +1
        elif col[2] == 2 and col[3] == 2:
            otherTacMap[(3-1)-(mod),(5-1)-share+2] =otherTacMap[(3-1)-(mod),(5-1)-share+2] +1
    elif col[0] == 3:
        n = col[1]
        mod = (n-1)%3
        share = (n-1)//3
        sumMap[(3-1)-(mod),(5-1)-share+2+3] = sumMap[(3-1)-(mod),(5-1)-share+2+3] +1
        if col[2] == 2 and col[3] == 1:
            vibeMap[(3-1)-(mod),(5-1)-share+2+3] = vibeMap[(3-1)-(mod),(5-1)-share+2+3] +1
        elif col[2] == 1:
            painMap[(3-1)-(mod),(5-1)-share+2+3] = painMap[(3-1)-(mod),(5-1)-share+2+3] +1
        elif col[2] == 3:
            nonfeelingMap[(3-1)-(mod),(5-1)-share+2+3] = nonfeelingMap[(3-1)-(mod),(5-1)-share+2+3] +1
        elif col[2] == 2 and col[3] == 2:
            otherTacMap[(3-1)-(mod),(5-1)-share+2+3] =otherTacMap[(3-1)-(mod),(5-1)-share+2+3] +1
    elif col[0] == 4:
        n = col[1]
        mod = (n-1)%3
        share = (n-1)//3
        sumMap[(3-1)-(mod),(5-1)-share+2+3+2] = sumMap[(3-1)-(mod),(5-1)-share+2+3+2] +1
        if col[2] == 2 and col[3] == 1:
            vibeMap[(3-1)-(mod),(5-1)-share+2+3+2] = vibeMap[(3-1)-(mod),(5-1)-share+2+3+2] +1
        elif col[2] == 1:
            painMap[(3-1)-(mod),(5-1)-share+2+3+2] = painMap[(3-1)-(mod),(5-1)-share+2+3+2] +1
        elif col[2] == 3:
            nonfeelingMap[(3-1)-(mod),(5-1)-share+2+3+2] = nonfeelingMap[(3-1)-(mod),(5-1)-share+2+3+2] +1
        elif col[2] == 2 and col[3] == 2:
            otherTacMap[(3-1)-(mod),(5-1)-share+2+3+2] =otherTacMap[(3-1)-(mod),(5-1)-share+2+3+2] +1
    elif col[0] == 5:
        n = col[1]
        mod = (n-1)%3
        share = (n-1)//3
        sumMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = sumMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +1
        if col[2] == 2 and col[3] == 1:
            vibeMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = vibeMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +1
        elif col[2] == 1:
            painMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = painMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +1
        elif col[2] == 3:
            nonfeelingMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = nonfeelingMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +1
        elif col[2] == 2 and col[3] == 2:
            otherTacMap[(3-1)-(mod),(5-1)-share+2+3+2+3] =otherTacMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +1
print(sumMap)
print(vibeMap)
print(painMap)
#比率に変える
df2= vibeMap/sumMap
df3 = painMap/sumMap
df4 = nonfeelingMap/sumMap
df5 = otherTacMap/sumMap
# df2 = pd.DataFrame(df2)
# df3 = pd.DataFrame(df3)
# df4 = pd.DataFrame(df4)
#df2 = sns.load_dataset("df2")
#df2 = df2.pivot("Model", "Task", "Score")

#反転
#for i = 0 14 range
# new(14-i) = df()
#


#触覚
plt.figure(figsize = (10,2))
s = sns.heatmap(df2,annot=True, cmap='Reds',fmt='g',linewidths=.5)

plt.title('tactile')
s.set_xlabel('Column', fontsize=10)
s.set_ylabel('Row', fontsize=10)
plt.savefig('data/hikensha1_first_tactile_heatmap.png')
plt.clf()
plt.close()

#痛覚
plt.figure(figsize = (10,2))
s2 = sns.heatmap(df3,annot=True, cmap='Reds',fmt='g',linewidths=.5)
plt.title('pain')
s2.set_xlabel('Column', fontsize=10)
s2.set_ylabel('Row', fontsize=10)
plt.savefig('data/hikensha1_first_pain_heatmap.png')
plt.clf()
plt.close()

#感覚なし
plt.figure(figsize = (10,2))
s2 = sns.heatmap(df4,annot=True, cmap='Reds',fmt='g',linewidths=.5)
plt.title('nonfeeling')
s2.set_xlabel('Column', fontsize=10)
s2.set_ylabel('Row', fontsize=10)
plt.savefig('data/hikensha1_first_nonfeeling_heatmap.png')
plt.clf()
plt.close()

#振動以外感覚
plt.figure(figsize = (10,2))
s2 = sns.heatmap(df5,annot=True, cmap='Reds',fmt='g',linewidths=.5)
plt.title('other tactile feeling(not vibe)')
s2.set_xlabel('Column', fontsize=10)
s2.set_ylabel('Row', fontsize=10)
plt.savefig('data/hikensha1_first_otherTac_heatmap.png')
plt.clf()
plt.close()



          0    1    2    3    4    5    6    7    8    9    ...  740  741  \
グループ（番目）    2    2    2    2    2    2    2    2    2    2  ...    4    4   
刺激点(番目)     3    1   15   12   13    2   11   10    8    4  ...   12   14   
生起感覚        2    2    1    2    2    3    3    3    3    3  ...    3    2   
追加質問        1    1    0    1    1    0    0    0    0    0  ...    0    1   

          742  743  744  745  746  747  748  749  
グループ（番目）    4    4    4    4    4    4    4    4  
刺激点(番目)    11    5    8    1    7   10   15    2  
生起感覚        3    2    3    2    3    3    3    3  
追加質問        0    1    0    1    0    0    0    0  

[4 rows x 750 columns]
[[10. 10. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 10. 10. 10.]
 [10. 10. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 10. 10. 10.]
 [10. 10. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 10. 10. 10.]]
[[ 7.  7. 10. 19.  4. 13. 10. 10. 10.  4.  7.  1.  4.  8.  1.]
 [ 2.  0.  9.  0.  0. 15.  4. 14.  0.  1. 12.  5.  0.  3.  6.]
 [ 7.  5. 10.  7.  

In [ ]:
import numpy as np
import pandas as pd
import locale

import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

# csvファイルを読み込んでdfへ入れる(DataFrameオブジェクト)
df = pd.read_csv('No_10_D2_E.csv', encoding="utf_8",header = 0)
#usecols=[2,3,4,5,6,7,8]
# df.Tで行と列を入れ替える
#print(df.T)

df1 = pd.read_csv('No_10_D2_E.csv', encoding="utf_8",header = 0 ,usecols=[2,3,6,7])
print(df1.T)
#usecols=[2,3,5,6,7,8]
#要素がgroupが1, 1,2,3,4,5 -> n
# col 2,3,2,3
#全体刺激回数分布図
sumMap = np.zeros((3,15))
#振動回数分布図

vibeMap = np.zeros((3,15))
otherTacMap = np.zeros((3,15))
painMap=np.zeros((3,15))
nonfeelingMap = np.zeros((3,15))
for col in df1.values:
    #group is 1
    if col[0] == 1:
      #  print(col)
        #nに刺激点指定
        n = col[1]
        #n-1をして式を簡単に
        mod = (n-1)%3
        share = (n-1)//3
        sumMap[(3-1)-(mod),(5-1)-share] = sumMap[(3-1)-(mod),(5-1)-share] +1
        if col[2] == 2 and col[3] == 1:
            vibeMap[(3-1)-(mod),(5-1)-share] = vibeMap[(3-1)-(mod),(5-1)-share] +1
        elif col[2] == 1:
            painMap[(3-1)-(mod),(5-1)-share] = painMap[(3-1)-(mod),(5-1)-share] +1
        elif col[2] == 3:
            nonfeelingMap[(3-1)-(mod),(5-1)-share] = nonfeelingMap[(3-1)-(mod),(5-1)-share] +1
        elif col[2] == 2 and col[3] == 2:
            otherTacMap[(3-1)-(mod),(5-1)-share] =otherTacMap[(3-1)-(mod),(5-1)-share] +1
    elif col[0] == 2:
        n = col[1]
        mod = (n-1)%3
        share = (n-1)//3
        sumMap[(3-1)-(mod),(5-1)-share+2] = sumMap[(3-1)-(mod),(5-1)-share+2] +1
        if col[2] == 2 and col[3] == 1:
            vibeMap[(3-1)-(mod),(5-1)-share+2] = vibeMap[(3-1)-(mod),(5-1)-share+2] +1
        elif col[2] == 1:
            painMap[(3-1)-(mod),(5-1)-share+2] = painMap[(3-1)-(mod),(5-1)-share+2] +1
        elif col[2] == 3:
            nonfeelingMap[(3-1)-(mod),(5-1)-share+2] = nonfeelingMap[(3-1)-(mod),(5-1)-share+2] +1
        elif col[2] == 2 and col[3] == 2:
            otherTacMap[(3-1)-(mod),(5-1)-share+2] =otherTacMap[(3-1)-(mod),(5-1)-share+2] +1
    elif col[0] == 3:
        n = col[1]
        mod = (n-1)%3
        share = (n-1)//3
        sumMap[(3-1)-(mod),(5-1)-share+2+3] = sumMap[(3-1)-(mod),(5-1)-share+2+3] +1
        if col[2] == 2 and col[3] == 1:
            vibeMap[(3-1)-(mod),(5-1)-share+2+3] = vibeMap[(3-1)-(mod),(5-1)-share+2+3] +1
        elif col[2] == 1:
            painMap[(3-1)-(mod),(5-1)-share+2+3] = painMap[(3-1)-(mod),(5-1)-share+2+3] +1
        elif col[2] == 3:
            nonfeelingMap[(3-1)-(mod),(5-1)-share+2+3] = nonfeelingMap[(3-1)-(mod),(5-1)-share+2+3] +1
        elif col[2] == 2 and col[3] == 2:
            otherTacMap[(3-1)-(mod),(5-1)-share+2+3] =otherTacMap[(3-1)-(mod),(5-1)-share+2+3] +1
    elif col[0] == 4:
        n = col[1]
        mod = (n-1)%3
        share = (n-1)//3
        sumMap[(3-1)-(mod),(5-1)-share+2+3+2] = sumMap[(3-1)-(mod),(5-1)-share+2+3+2] +1
        if col[2] == 2 and col[3] == 1:
            vibeMap[(3-1)-(mod),(5-1)-share+2+3+2] = vibeMap[(3-1)-(mod),(5-1)-share+2+3+2] +1
        elif col[2] == 1:
            painMap[(3-1)-(mod),(5-1)-share+2+3+2] = painMap[(3-1)-(mod),(5-1)-share+2+3+2] +1
        elif col[2] == 3:
            nonfeelingMap[(3-1)-(mod),(5-1)-share+2+3+2] = nonfeelingMap[(3-1)-(mod),(5-1)-share+2+3+2] +1
        elif col[2] == 2 and col[3] == 2:
            otherTacMap[(3-1)-(mod),(5-1)-share+2+3+2] =otherTacMap[(3-1)-(mod),(5-1)-share+2+3+2] +1
    elif col[0] == 5:
        n = col[1]
        mod = (n-1)%3
        share = (n-1)//3
        sumMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = sumMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +1
        if col[2] == 2 and col[3] == 1:
            vibeMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = vibeMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +1
        elif col[2] == 1:
            painMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = painMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +1
        elif col[2] == 3:
            nonfeelingMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = nonfeelingMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +1
        elif col[2] == 2 and col[3] == 2:
            otherTacMap[(3-1)-(mod),(5-1)-share+2+3+2+3] =otherTacMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +1
print(sumMap)
print(vibeMap)
print(painMap)
#比率に変える
df12= vibeMap/sumMap
df13 = painMap/sumMap
df14 = nonfeelingMap/sumMap
df15 = otherTacMap/sumMap

#差を求める
df22 =abs(df12- df2)
df23 = abs(df13 -df3)
df24 = abs(df14 -df4)
df25 = abs(df15 -df5)

#df2 = sns.load_dataset("df2")
#df2 = df2.pivot("Model", "Task", "Score")

#触覚
plt.figure(figsize = (10,2))
s = sns.heatmap(df12,annot=True, cmap='Reds',fmt='g',linewidths=.5)
s.set_xlabel('horizontal', fontsize=10)
s.set_ylabel('vertical', fontsize=10)
plt.title('tactile')
plt.savefig('data/hikensha1_second_tactile_heatmap.png')
plt.clf()
plt.close()

#痛覚
plt.figure(figsize = (10,2))
s2 = sns.heatmap(df13,annot=True, cmap='Reds',fmt='g',linewidths=.5)
s2.set_xlabel('horizontal', fontsize=10)
s2.set_ylabel('vertical', fontsize=10)
plt.title('pain')
plt.savefig('data/hikensha1_second_pain_heatmap.png')
plt.clf()
plt.close()

#感覚なし
plt.figure(figsize = (10,2))
s2 = sns.heatmap(df14,annot=True, cmap='Reds',fmt='g',linewidths=.5)
s2.set_xlabel('horizontal', fontsize=10)
s2.set_ylabel('vertical', fontsize=10)
plt.title('nonfeeling')
plt.savefig('data/hikensha1_second_nonfeeling_heatmap.png')
plt.clf()
plt.close()

#振動以外感覚
plt.figure(figsize = (10,2))
s2 = sns.heatmap(df5,annot=True, cmap='Reds',fmt='g',linewidths=.5)
s2.set_xlabel('horizontal', fontsize=10)
s2.set_ylabel('vertical', fontsize=10)
plt.title('other tactile feeling(not vibe)')
plt.savefig('data/hikensha1_second_otherTac_heatmap.png')
plt.clf()
plt.close()

#差分
#vibe
plt.figure(figsize = (10,2))
s2 = sns.heatmap(df22,annot=True, cmap='Reds',fmt='g',linewidths=.5)
s2.set_xlabel('horizontal', fontsize=10)
s2.set_ylabel('vertical', fontsize=10)
plt.title('tactile differential')
plt.savefig('data/hikensha1_tactile_differential_heatmap.png')
plt.clf()
plt.close()

#pain
plt.figure(figsize = (10,2))
s2 = sns.heatmap(df23,annot=True, cmap='Reds',fmt='g',linewidths=.5)
s2.set_xlabel('horizontal', fontsize=10)
s2.set_ylabel('vertical', fontsize=10)
plt.title('pain differential')
plt.savefig('data/hikensha1_pain_differential_heatmap.png')
plt.clf()
plt.close()

#nonfeeling
plt.figure(figsize = (10,2))
s2 = sns.heatmap(df24,annot=True, cmap='Reds',fmt='g',linewidths=.5)
s2.set_xlabel('horizontal', fontsize=10)
s2.set_ylabel('vertical', fontsize=10)
plt.title('nonfeeling differential')
plt.savefig('data/hikensha1_nonfeeling_differential_heatmap.png')
plt.clf()
plt.close()

#nonfeeling
plt.figure(figsize = (10,2))
s2 = sns.heatmap(df25,annot=True, cmap='Reds',fmt='g',linewidths=.5)
s2.set_xlabel('horizontal', fontsize=10)
s2.set_ylabel('vertical', fontsize=10)
plt.title('other tactile differential')
plt.savefig('data/hikensha1_otherfeel_differential_heatmap.png')
plt.clf()
plt.close()

          0    1    2    3    4    5    6    7    8    9    ...  740  741  \
グループ（番目）    4    4    4    4    4    4    4    4    4    4  ...    2    2   
刺激点(番目)     5    3    9    8   13    6    1    7   14   12  ...    8    9   
生起感覚        1    2    1    2    2    3    2    2    2    2  ...    3    3   
追加質問        0    1    0    1    1    0    1    1    1    1  ...    0    0   

          742  743  744  745  746  747  748  749  
グループ（番目）    2    2    2    2    2    2    2    2  
刺激点(番目)    14   15   10   11   12    3    1    5  
生起感覚        3    3    3    3    3    3    3    3  
追加質問        0    0    0    0    0    0    0    0  

[4 rows x 750 columns]
[[10. 10. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 10. 10. 10.]
 [10. 10. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 10. 10. 10.]
 [10. 10. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 10. 10. 10.]]
[[ 8.  9.  5. 13. 11. 12. 15.  4.  8.  4.  7.  8.  7.  8.  0.]
 [10.  4.  5.  8.  2.  4.  7. 12.  4. 11.  5.  2.  0.  3.  5.]
 [ 7.  9. 13.  1.  

In [ ]:
#電流値　時間
import numpy as np
import pandas as pd
import locale

import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

# csvファイルを読み込んでdfへ入れる(DataFrameオブジェクト)
df = pd.read_csv('No_10_D1_E.csv', encoding="utf_8",header = 0)
#usecols=[2,3,4,5,6,7,8]
# df.Tで行と列を入れ替える
#print(df.T)

df1 = pd.read_csv('No_10_D1_E.csv', encoding="utf_8",header = 0 ,usecols=[2,3,5,8])
print(df1.T)
#要素がgroupが1, 1,2,3,4,5 -> n
# col 2,3,2,3
#全体刺激回数分布図
sumMap = np.zeros((3,15))
#振動回数分布図
# vibeMap = np.zeros((3,15))
# painMap=np.zeros((3,15))
voltMap =np.zeros((3,15))
timeMap = np.zeros((3,15))
for col in df1.values:
    #group is 1
    if col[0] == 1:
      #  print(col)
        #nに刺激点指定
        n = col[1]
        #n-1をして式を簡単に
        mod =int( (n-1)%3)
        share = int((n-1)//3)
        sumMap[(3-1)-(mod),(5-1)-share] = sumMap[(3-1)-(mod),(5-1)-share] +1
        # if col[3] == 2 and col[4] == 1:
        #     vibeMap[(3-1)-(mod),(5-1)-share] = vibeMap[(3-1)-(mod),(5-1)-share] +1
        # elif col[3] == 1:
        #     painMap[(3-1)-(mod),(5-1)-share] = painMap[(3-1)-(mod),(5-1)-share] +1
        timeMap[(3-1)-(mod),(5-1)-share] = timeMap[(3-1)-(mod),(5-1)-share] +col[2]
        voltMap[(3-1)-(mod),(5-1)-share] = voltMap[(3-1)-(mod),(5-1)-share] + col[3]
    elif col[0] == 2:
        n = col[1]
        mod = int((n-1)%3)
        share = int((n-1)//3)
        sumMap[(3-1)-(mod),(5-1)-share+2] = sumMap[(3-1)-(mod),(5-1)-share+2] +1
        # if col[3] == 2 and col[4] == 1:
        #     vibeMap[(3-1)-(mod),(5-1)-share+2] = vibeMap[(3-1)-(mod),(5-1)-share+2] +1
        # elif col[3] == 1:
        #     painMap[(3-1)-(mod),(5-1)-share+2] = painMap[(3-1)-(mod),(5-1)-share+2] +1
        timeMap[(3-1)-(mod),(5-1)-share+2] = timeMap[(3-1)-(mod),(5-1)-share+2] +col[2]
        voltMap[(3-1)-(mod),(5-1)-share+2] = voltMap[(3-1)-(mod),(5-1)-share+2] + col[3]

    elif col[0] == 3:
        n = col[1]
        mod = int((n-1)%3)
        share = int((n-1)//3)
        sumMap[(3-1)-(mod),(5-1)-share+2+3] = sumMap[(3-1)-(mod),(5-1)-share+2+3] +1
        # if col[3] == 2 and col[4] == 1:
        #     vibeMap[(3-1)-(mod),(5-1)-share+2+3] = vibeMap[(3-1)-(mod),(5-1)-share+2+3] +1
        # elif col[3] == 1:
        #     painMap[(3-1)-(mod),(5-1)-share+2+3] = painMap[(3-1)-(mod),(5-1)-share+2+3] +1
        timeMap[(3-1)-(mod),(5-1)-share+2+3] = timeMap[(3-1)-(mod),(5-1)-share+2+3] +col[2]
        voltMap[(3-1)-(mod),(5-1)-share+2+3] = voltMap[(3-1)-(mod),(5-1)-share+2+3] + col[3]
    elif col[0] == 4:
        n = col[1]
        mod = int((n-1)%3)
        share = int((n-1)//3)
        sumMap[(3-1)-(mod),(5-1)-share+2+3+2] = sumMap[(3-1)-(mod),(5-1)-share+2+3+2] +1
        # if col[3] == 2 and col[4] == 1:
        #     vibeMap[(3-1)-(mod),(5-1)-share+2+3+2] = vibeMap[(3-1)-(mod),(5-1)-share+2+3+2] +1
        # elif col[3] == 1:
        #     painMap[(3-1)-(mod),(5-1)-share+2+3+2] = painMap[(3-1)-(mod),(5-1)-share+2+3+2] +1
        timeMap[(3-1)-(mod),(5-1)-share+2+3+2] = timeMap[(3-1)-(mod),(5-1)-share+2+3+2] +col[2]
        voltMap[(3-1)-(mod),(5-1)-share+2+3+2] = voltMap[(3-1)-(mod),(5-1)-share+2+3+2] + col[3]
    elif col[0] == 5:
        n = col[1]
        mod = int((n-1)%3)
        share = int((n-1)//3)
        sumMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = sumMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +1
        # if col[3] == 2 and col[4] == 1:
        #     vibeMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = vibeMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +1
        # elif col[3] == 1:
        #     painMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = painMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +1
        timeMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = timeMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +col[2]
        voltMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = voltMap[(3-1)-(mod),(5-1)-share+2+3+2+3] + col[3]
#print(sumMap)
# print(vibeMap)
# print(painMap)
#比率に変える
df2= timeMap/sumMap
df3 = voltMap/sumMap
# df2 = pd.DataFrame(df2)
# df3 = pd.DataFrame(df3)

df11 = pd.read_csv('No_10_D2_E.csv', encoding="utf_8",header = 0 ,usecols=[2,3,5,8])
#print(df11.T)
#要素がgroupが1, 1,2,3,4,5 -> n
#全体刺激回数分布図
sumMap = np.zeros((3,15))
#振動回数分布図
# vibeMap = np.zeros((3,15))
# painMap=np.zeros((3,15))
voltMap =np.zeros((3,15))
timeMap = np.zeros((3,15))
for col in df11.values:
    #group is 1
    if col[0] == 1:
      #  print(col)
        #nに刺激点指定
        n = col[1]
        #n-1をして式を簡単に
        mod =int( (n-1)%3)
        share = int((n-1)//3)
        sumMap[(3-1)-(mod),(5-1)-share] = sumMap[(3-1)-(mod),(5-1)-share] +1
        # if col[3] == 2 and col[4] == 1:
        #     vibeMap[(3-1)-(mod),(5-1)-share] = vibeMap[(3-1)-(mod),(5-1)-share] +1
        # elif col[3] == 1:
        #     painMap[(3-1)-(mod),(5-1)-share] = painMap[(3-1)-(mod),(5-1)-share] +1
        timeMap[(3-1)-(mod),(5-1)-share] = timeMap[(3-1)-(mod),(5-1)-share] +col[2]
        voltMap[(3-1)-(mod),(5-1)-share] = voltMap[(3-1)-(mod),(5-1)-share] + col[3]
    elif col[0] == 2:
        n = col[1]
        mod = int((n-1)%3)
        share = int((n-1)//3)
        sumMap[(3-1)-(mod),(5-1)-share+2] = sumMap[(3-1)-(mod),(5-1)-share+2] +1
        # if col[3] == 2 and col[4] == 1:
        #     vibeMap[(3-1)-(mod),(5-1)-share+2] = vibeMap[(3-1)-(mod),(5-1)-share+2] +1
        # elif col[3] == 1:
        #     painMap[(3-1)-(mod),(5-1)-share+2] = painMap[(3-1)-(mod),(5-1)-share+2] +1
        timeMap[(3-1)-(mod),(5-1)-share+2] = timeMap[(3-1)-(mod),(5-1)-share+2] +col[2]
        voltMap[(3-1)-(mod),(5-1)-share+2] = voltMap[(3-1)-(mod),(5-1)-share+2] + col[3]

    elif col[0] == 3:
        n = col[1]
        mod = int((n-1)%3)
        share = int((n-1)//3)
        sumMap[(3-1)-(mod),(5-1)-share+2+3] = sumMap[(3-1)-(mod),(5-1)-share+2+3] +1
        # if col[3] == 2 and col[4] == 1:
        #     vibeMap[(3-1)-(mod),(5-1)-share+2+3] = vibeMap[(3-1)-(mod),(5-1)-share+2+3] +1
        # elif col[3] == 1:
        #     painMap[(3-1)-(mod),(5-1)-share+2+3] = painMap[(3-1)-(mod),(5-1)-share+2+3] +1
        timeMap[(3-1)-(mod),(5-1)-share+2+3] = timeMap[(3-1)-(mod),(5-1)-share+2+3] +col[2]
        voltMap[(3-1)-(mod),(5-1)-share+2+3] = voltMap[(3-1)-(mod),(5-1)-share+2+3] + col[3]
    elif col[0] == 4:
        n = col[1]
        mod = int((n-1)%3)
        share = int((n-1)//3)
        sumMap[(3-1)-(mod),(5-1)-share+2+3+2] = sumMap[(3-1)-(mod),(5-1)-share+2+3+2] +1
        # if col[3] == 2 and col[4] == 1:
        #     vibeMap[(3-1)-(mod),(5-1)-share+2+3+2] = vibeMap[(3-1)-(mod),(5-1)-share+2+3+2] +1
        # elif col[3] == 1:
        #     painMap[(3-1)-(mod),(5-1)-share+2+3+2] = painMap[(3-1)-(mod),(5-1)-share+2+3+2] +1
        timeMap[(3-1)-(mod),(5-1)-share+2+3+2] = timeMap[(3-1)-(mod),(5-1)-share+2+3+2] +col[2]
        voltMap[(3-1)-(mod),(5-1)-share+2+3+2] = voltMap[(3-1)-(mod),(5-1)-share+2+3+2] + col[3]
    elif col[0] == 5:
        n = col[1]
        mod = int((n-1)%3)
        share = int((n-1)//3)
        sumMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = sumMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +1
        # if col[3] == 2 and col[4] == 1:
        #     vibeMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = vibeMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +1
        # elif col[3] == 1:
        #     painMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = painMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +1
        timeMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = timeMap[(3-1)-(mod),(5-1)-share+2+3+2+3] +col[2]
        voltMap[(3-1)-(mod),(5-1)-share+2+3+2+3] = voltMap[(3-1)-(mod),(5-1)-share+2+3+2+3] + col[3]

#df2 = sns.load_dataset("df2")
#df2 = df2.pivot("Model", "Task", "Score")
df12= timeMap/sumMap
df13 = voltMap/sumMap

#time
plt.figure(figsize = (20,4))
s = sns.heatmap(df12,annot=True, cmap='Reds',fmt='g',linewidths=.5)
s.set_xlabel('horizontal', fontsize=10)
s.set_ylabel('vertical', fontsize=10)
plt.title('time')
plt.savefig('data/hikensha1_second_time_heatmap.png')
plt.clf()
plt.close()

#電圧
plt.figure(figsize = (10,2))
s2 = sns.heatmap(df13,annot=True, cmap='Reds',fmt='g',linewidths=.5)
s2.set_xlabel('horizontal', fontsize=10)
s2.set_ylabel('vertical', fontsize=10)
plt.title('volt')
plt.savefig('data/hikensha1_second_volt_heatmap.png')
plt.clf()
plt.close()


#差分 volt
df23 = abs(df13-df3)

plt.figure(figsize = (10,2))
s2 = sns.heatmap(df23,annot=True, cmap='Reds',fmt='g',linewidths=.5)
s2.set_xlabel('horizontal', fontsize=10)
s2.set_ylabel('vertical', fontsize=10)
plt.title('volt diff')
plt.savefig('data/hikensha1_voltdiff_heatmap.png')
plt.clf()
plt.close()

              0        1        2       3       4        5        6    \
グループ（番目）    2.000    2.000    2.000    2.00    2.00    2.000    2.000   
刺激点(番目)     3.000    1.000   15.000   12.00   13.00    2.000   11.000   
刺激時間(s)     3.121    0.558    3.721    4.32    4.58   12.359   19.458   
電流指定値     250.000  190.000  190.000  150.00  210.00  250.000  250.000   

              7        8        9    ...      740      741      742      743  \
グループ（番目）    2.000    2.000    2.000  ...    4.000    4.000    4.000    4.000   
刺激点(番目)    10.000    8.000    4.000  ...   12.000   14.000   11.000    5.000   
刺激時間(s)    26.431   32.838   39.031  ...   35.955    4.369   11.209    0.455   
電流指定値     230.000  250.000  250.000  ...  110.000  230.000  250.000  210.000   

              744     745      746      747      748      749  
グループ（番目）    4.000    4.00    4.000    4.000    4.000    4.000  
刺激点(番目)     8.000    1.00    7.000   10.000   15.000    2.000  
刺激時間(s)     6.418    4.33   10.738   17.5